/**
 * Copyright (C) 2012 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thingml.rtsync.ui;

import java.awt.Color;
import org.thingml.rtcharts.swing.*;
import org.thingml.rtsync.core.*;

/**
 *
 * @author ffl
 */
public class TimeSyncDelayErrorFrame extends javax.swing.JFrame implements ITimeSynchronizerLogger {

    protected DataBuffer bxyerr = new DataBuffer(2, 100);
    
    protected GraphBuffer berr = new GraphBuffer(100);
    protected GraphBuffer bdelay = new GraphBuffer(100);
    
   
    protected TimeSynchronizer ts = null;
    
    /**
     * Creates new form TimeSynchronizerFrame
     */
    public TimeSyncDelayErrorFrame(TimeSynchronizer ts) {
        initComponents();
        this.ts = ts;
        ts.addLogger(this);
        ((XYGraphPanel)jPanel2).start();
        ((GraphPanel)jPanel3).start();
        ((GraphPanel)jPanel4).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new XYGraphPanel(bxyerr, "Error vs Delay (ms)", 0, 150, 25, -50, 50, 10, new java.awt.Color(0, 204, 51));
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new BarGraphPanel(bdelay, "Calculated delay (ms)", 0, 200, 50, new java.awt.Color(0, 204, 51));
        jPanel4 = new BarGraphPanel(berr, "Error", -40, 40, 20, new java.awt.Color(0, 204, 51));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));
        jPanel1.add(jPanel2);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel6.add(jPanel3);
        jPanel6.add(jPanel4);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
          if (ts != null) {
              ts.removeLogger(this);
          }
          ((XYGraphPanel)jPanel2).stop();
          ((GraphPanel)jPanel3).stop();
          ((GraphPanel)jPanel4).stop();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void timeSyncStart() {
        
    }

    @Override
    public void timeSyncStop() {
        
    }

    @Override
    public void timeSyncLog(String time, long ts, long tmt, long tmr, long delay, long offs, long error, long errorSum, long zeroOffset, long regOffsMs, int skipped, long tsOffset) {
        int del = (int) delay;
        //int err = (int) (offs - regOffsMs); // Use limited error instead
        int err = (int) error; 
        bxyerr.appendDataRow(new int[] {del, err});
        berr.insertData(err);
        bdelay.insertData(del);
//        bdrop.insertData(0);
    }

    @Override
    public void timeSyncPong(int delay, int dtt, int dtr, int dts) {
        
    }

    @Override
    public void timeSyncReady() {
    }

    @Override
    public void timeSyncWrongSequence(int pingSeqNum, int pongSeqNum) {
    }

    @Override
    public void timeSyncDtsFilter(int dts) {
      //  bdrop.insertData(dts);
    }

    @Override
    public void timeSyncErrorFilter(int error) {
    }

    @Override
    public void timeSyncPingTimeout(int pingSeqNum, long tmt) {
        
    }

    @Override
    public void timeSyncPongRaw(String time, int rcvPingSeqNum, int expectedPingSeqNum, long tmt, long tmr, long ts) {

    }
}
